language: node_js

node_js:
  - 12.18.2

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - sshpass

install:
  - ssh-keyscan ${gluten_ip} >> ~/.ssh/known_hosts

script:
  - npm install
  - npm run build
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'rm -rf /root/gluten/dist'
  - sshpass -p ${gluten_pwd} scp -o StrictHostKeyChecking=no -r ./dist root@${gluten_ip}:/root/gluten/dist
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'systemctl restart caddy'

branches:
  only:
    - master

notifications:
  email: true
