language: node_js

node_js:
  - 12.18.2

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'rm -rf /root/gluten/dist'
  - sshpass -p ${gluten_pwd} scp -o StrictHostKeyChecking=no ./dist root@${gluten_ip}:/root/gluten/dist
  - sshpass -p ${gluten_pwd} ssh -o StrictHostKeyChecking=no root@${gluten_ip}  'systemctl restart caddy'

branches:
  only:
    - master
